<?php echo $this->doctype() ?>

<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>

        <?php
        echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/styles/style.css')
                ->prependStylesheet($this->baseUrl() . '/styles/form.css');
        ?>

        <?php echo $this->JQuery()->enable(); ?>

    </head>

    <body>

        <div id="barrinha"></div>
        <div id="estrutura">


            <div id="topo">
                <h1>ZfShop</h1>
                <h2>Sistemas administrativo</h2>
            </div>

            <div class="clearfix"></div>

            <div id="menu-horizontal">
                <?php echo $this->navigation()
                        ->menu()
                        ->setMaxDepth(0)
                        ->render(); ?>
            </div>

            <div class="clearfix"></div>


            <div id="content">
                <div id="breadcrumbs">
                    <h3>
                        <?php echo $this->navigation()
                                ->breadcrumbs()
                                ->setMinDepth(0)
                                ->setMaxDepth(2)
                                ->setSeparator(" : ");
                        ?>
                    </h3>
                </div>

                <?php echo $this->layout()->content; ?>

                <div class="clearfix"></div>
            </div>

            <div class="clearfix"></div>

        </div>
        <div id="footer">
            <p>ZFShop - Todos os direitos reservados</p></div>
    </body>
</html>