<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Cidade</th>
            <th>Estado</th>
            <th width="8%">Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->clientes as $cliente): ?>
            <tr>
                <td><?php echo $this->escape($cliente->getNome()); ?></td>
                <td><?php echo $this->escape($cliente->getEmail()); ?></td>
                <td><?php echo $this->escape($cliente->getCidade()); ?></td>
                <td><?php echo $this->escape($cliente->getEstado()); ?></td>
                <td>
                    <a href="<?php echo $this->url(array('controller'=>'clientes', 'action'=>'edit','module'=>'admin','id'=>$cliente->getId()),null,1)?>">
                        <img src="<?php echo $this->baseUrl("/images/icons/edit.png");?>" alt="Editar">
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->clientes,'Sliding','paginator.phtml'); ?>