<?php echo $this->doctype(); ?>

<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <?php
        echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/styles/style.css')
                ->prependStylesheet($this->baseUrl() . '/styles/frontend.css')
                ->prependStylesheet($this->baseUrl() . '/styles/form.css')
        ?>

    </head>

    <body>

        <div id="barrinha"></div>
        <div id="estrutura">


            <div id="topo">
                <h1>ZfShop</h1>
                <div id="menu-superior">
                    <ul>
                        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, 1); ?>">Home</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'carrinho', 'action' => 'index'), null, 1); ?>">Carrinho de compras</a></li>
                    </ul>
                </div>
            </div>

            <div class="clearfix"></div>

            <div id="barra">
                <div><?php echo $this->placeholder('welcome'); ?></div>
            </div>
            <div id="banner-principal">

            </div>


            <div id="categorias">
                <h3>Categorias</h3>
                <?php echo $this->placeholder('categorias'); ?>
            </div>

            <div id="conteudo">
                <?php echo $this->layout()->content; ?>

            </div>

            <div class="clearfix"></div>

        </div>
        <div id="footer">
            <p>ZFShop - Todos os direitos reservados</p></div>
    </body>
</html>