<p><a href="<?php echo $this->url(array('controller' => 'categorias', 'action' => 'add', 'module' => 'admin'), null, 1); ?>">Novo</a></p>

<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th width="8%">Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->categorias as $categoria): ?>
            <tr>
                <td><?php echo $this->escape($categoria->getNome()) ?></td>
                <td><?php echo $this->escape($categoria->getDescricao()) ?></td>
                <td>
                    <a href="<?php echo $this->url(array('controller' => 'categorias', 'action' => 'edit', 'module' => 'admin', 'id' => $categoria->getId()), null, 1) ?>">
                        <img src="<?php echo $this->baseUrl("/images/icons/edit.png"); ?>" alt="Editar">
                    </a>
                    &nbsp;
                    <a href="<?php echo $this->url(array('controller' => 'categorias', 'action' => 'delete', 'module' => 'admin', 'id' => $categoria->getId()), null, 1) ?>">
                        <img src="<?php echo $this->baseUrl("/images/icons/delete.png"); ?>" alt="Delete">
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->categorias,"Sliding","paginator.phtml"); ?>